# Generated by Django 2.2.1 on 2019-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
