# Generated by Django 2.2.1 on 2019-05-29 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0004_auto_20190529_0650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
