# Generated by Django 2.2.1 on 2019-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0005_auto_20190529_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
