# Generated by Django 2.2.1 on 2019-06-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0006_language_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_1', to='idionative.Word')),
                ('word_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_2', to='idionative.Word')),
            ],
        ),
        migrations.CreateModel(
            name='SameWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sameword_1', to='idionative.Word')),
                ('word_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sameword_2', to='idionative.Word')),
            ],
            options={
                'verbose_name_plural': 'same_words',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idionative.Word')),
            ],
        ),
    ]
