# Generated by Django 2.2.1 on 2019-06-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0007_meaning_samewords_synonym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samewords',
            name='word_1',
        ),
        migrations.RemoveField(
            model_name='samewords',
            name='word_2',
        ),
        migrations.AddField(
            model_name='samewords',
            name='de_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='germanWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='en_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='englishWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='es_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='spanishWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='gl_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='galicianWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='ja_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='japaneseWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='ko_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='koreanWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='nl_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dutchWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='pt_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='portugueseWord', to='idionative.Word'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samewords',
            name='vi_word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vietnameseWord', to='idionative.Word'),
            preserve_default=False,
        ),
    ]
