# Generated by Django 2.2.1 on 2019-06-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0009_news_language_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='language_news',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='idionative.Language'),
        ),
    ]
