# Generated by Django 2.2.1 on 2019-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0010_auto_20190607_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(default='<django.db.models.fields.charfield>', max_length=200),
        ),
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.CharField(default='<django.db.models.fields.charfield>', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
