# Generated by Django 2.2.1 on 2019-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0012_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_order',
            field=models.IntegerField(default=1),
        ),
    ]
