# Generated by Django 2.2.1 on 2019-06-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0013_page_page_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_type',
        ),
        migrations.AddField(
            model_name='meaning',
            name='word_type',
            field=models.CharField(choices=[('N', 'Noun'), ('Adj', 'Adjective'), ('Adv', 'Adverb'), ('Verb', 'Verb'), ('Pron', 'Pronoun'), ('Prep', 'Preposition')], default='N', max_length=4),
        ),
    ]
