# Generated by Django 2.2.1 on 2019-06-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idionative', '0016_auto_20190613_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
